name: Zbuduj i opublikuj strone 11ty

on:
  push:
    branches:
      - main
  workflow_dispatch:

# NOWA REGUŁA: Automatyczne zabijanie zawieszonych procesów!
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4
      
      - name: Instalacja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalacja zaleznosci
        run: npm install
        
      - name: Zbudowanie strony (Eleventy)
        run: npx @11ty/eleventy
        
      - name: Konfiguracja GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Przygotowanie plikow do publikacji
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
      - name: Publikacja na GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
